/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Ends this device's session. Idempotent: succeeds even if already signed out.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users Me */
        get: operations["read_users_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description XP per day over the last week and XP per skill, both from the activity log.
         */
        get: operations["get_dashboard_api_v1_users_me_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_users_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Onboarding
         * @description Saves the answers and marks the user onboarded. Submitting again updates the answers.
         */
        post: operations["submit_onboarding_api_v1_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Levels */
        get: operations["list_levels_api_v1_levels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_v1_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lessons */
        get: operations["list_lessons_api_v1_courses__course_id__lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson
         * @description The lesson plus what it contains, so the client knows which practices to offer.
         */
        get: operations["get_lesson_api_v1_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lesson Vocabulary */
        get: operations["list_lesson_vocabulary_api_v1_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Cards due now. New cards enter the schedule the first time they are reviewed.
         */
        get: operations["review_queue_api_v1_vocabulary_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_vocabulary_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading/passages/{passage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Passage */
        get: operations["get_passage_api_v1_reading_passages__passage_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reading/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Attempt */
        post: operations["submit_attempt_api_v1_reading_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listening/practices/{practice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice */
        get: operations["get_practice_api_v1_listening_practices__practice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listening/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Attempt */
        post: operations["submit_attempt_api_v1_listening_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/speaking/dialogues/{dialogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dialogue */
        get: operations["get_dialogue_api_v1_speaking_dialogues__dialogue_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/speaking/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Attempt
         * @description Rates each transcript against the scripted line; the expected text always comes from the dialogue.
         */
        post: operations["submit_attempt_api_v1_speaking_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/speaking/pronunciation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate Pronunciation
         * @description Per-line feedback while practising; earns no XP.
         */
        post: operations["rate_pronunciation_api_v1_speaking_pronunciation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/speaking/kaiwa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kaiwa Turn
         * @description The next line of a free conversation with the AI partner.
         */
        post: operations["kaiwa_turn_api_v1_speaking_kaiwa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/writing/kanji/{practice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kanji Practice */
        get: operations["get_kanji_practice_api_v1_writing_kanji__practice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/writing/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate
         * @description Rates the drawing against the practice's kanji (taken from the database, never from the client).
         */
        post: operations["evaluate_api_v1_writing_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gamification/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_gamification_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gamification/hearts/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refill Hearts */
        post: operations["refill_hearts_api_v1_gamification_hearts_refill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/tokenize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tokenize Text */
        post: operations["tokenize_text_api_v1_nlp_tokenize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessTokenData
         * @description The refresh token is never in the body; it is set as an httpOnly cookie.
         */
        AccessTokenData: {
            /** Userid */
            userId: number;
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             * @constant
             */
            tokenType: "bearer";
            /** Expiresin */
            expiresIn: number;
        };
        /** CourseListResponse */
        CourseListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            /** Data */
            data: components["schemas"]["CourseRead"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** CourseRead */
        CourseRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Status */
            status: string | null;
            /** Levelid */
            levelId: number;
            /** Sortorder */
            sortOrder: number | null;
        };
        /** DailyActivity */
        DailyActivity: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Xp */
            xp: number;
        };
        /** DashboardData */
        DashboardData: {
            user: components["schemas"]["DashboardUser"];
            /** Activity */
            activity: components["schemas"]["DailyActivity"][];
            /** Skills */
            skills: components["schemas"]["SkillProgress"][];
        };
        /** DashboardResponse */
        DashboardResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["DashboardData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** DashboardUser */
        DashboardUser: {
            /** Name */
            name: string;
            /** Xp */
            xp: number;
            /** Streak */
            streak: number;
            /** Level */
            level: string | null;
            /** Avatarurl */
            avatarUrl: string;
        };
        /** DialogueExchangeRead */
        DialogueExchangeRead: {
            /** Id */
            id: number;
            /** Orderindex */
            orderIndex: number;
            /** Speaker */
            speaker: string;
            /** Jatext */
            jaText: string;
            /** Jaromaji */
            jaRomaji: string;
            /** Entext */
            enText: string;
        };
        /** DialogueRead */
        DialogueRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Xpreward */
            xpReward: number;
            /**
             * Exchanges
             * @default []
             */
            exchanges: components["schemas"]["DialogueExchangeRead"][];
        };
        /** DialogueResponse */
        DialogueResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["DialogueRead"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** DialogueTurnSubmission */
        DialogueTurnSubmission: {
            /** Exchangeid */
            exchangeId: number;
            /** Transcript */
            transcript: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Success
             * @default false
             */
            success: boolean;
            /** Businesscode */
            businessCode: string;
            /** Message */
            message: string;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["ErrorDetail"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** EvaluateWritingData */
        EvaluateWritingData: {
            /** Attemptid */
            attemptId: number;
            /** Score */
            score: number;
            /** Feedback */
            feedback: string;
            /** Xpearned */
            xpEarned: number;
        };
        /**
         * EvaluateWritingRequest
         * @description The target kanji is loaded from the KanjiPractice row, not taken from the client.
         */
        EvaluateWritingRequest: {
            /** Kanjipracticeid */
            kanjiPracticeId: number;
            /** Imagebase64 */
            imageBase64: string;
        };
        /** EvaluateWritingResponse */
        EvaluateWritingResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["EvaluateWritingData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** GamificationStatusData */
        GamificationStatusData: {
            /** Xp */
            xp: number;
            /** Hearts */
            hearts: number;
            /** Streak */
            streak: number;
            /** Gems */
            gems: number;
        };
        /** GamificationStatusResponse */
        GamificationStatusResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["GamificationStatusData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** GenerateKaiwaRequest */
        GenerateKaiwaRequest: {
            /** History */
            history: components["schemas"]["KaiwaHistoryItem"][];
        };
        /** GenerateKaiwaResponse */
        GenerateKaiwaResponse: {
            /** Content */
            content: string;
            /** Romaji */
            romaji: string;
            /** Translation */
            translation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KaiwaHistoryItem */
        KaiwaHistoryItem: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** KanjiPracticeRead */
        KanjiPracticeRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Kanji */
            kanji: string;
            /** Difficulty */
            difficulty: string | null;
            /** Xpreward */
            xpReward: number;
        };
        /** KanjiPracticeResponse */
        KanjiPracticeResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["KanjiPracticeRead"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** LessonDetailRead */
        LessonDetailRead: {
            /** Id */
            id: number;
            /** Courseid */
            courseId: number;
            /** Title */
            title: string;
            /** Content */
            content: string | null;
            /** Difficulty */
            difficulty: string | null;
            /** Estimatedminutes */
            estimatedMinutes: number | null;
            /** Status */
            status: string | null;
            /** Sortorder */
            sortOrder: number | null;
            /** Vocabularycount */
            vocabularyCount: number;
            /**
             * Readingpassages
             * @default []
             */
            readingPassages: components["schemas"]["PracticeRef"][];
            /**
             * Dialogues
             * @default []
             */
            dialogues: components["schemas"]["PracticeRef"][];
            /**
             * Kanjipractices
             * @default []
             */
            kanjiPractices: components["schemas"]["PracticeRef"][];
            /**
             * Listeningpractices
             * @default []
             */
            listeningPractices: components["schemas"]["PracticeRef"][];
        };
        /** LessonDetailResponse */
        LessonDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["LessonDetailRead"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** LessonListResponse */
        LessonListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            /** Data */
            data: components["schemas"]["LessonRead"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** LessonRead */
        LessonRead: {
            /** Id */
            id: number;
            /** Courseid */
            courseId: number;
            /** Title */
            title: string;
            /** Content */
            content: string | null;
            /** Difficulty */
            difficulty: string | null;
            /** Estimatedminutes */
            estimatedMinutes: number | null;
            /** Status */
            status: string | null;
            /** Sortorder */
            sortOrder: number | null;
        };
        /** ListeningAnswerSubmission */
        ListeningAnswerSubmission: {
            /** Questionid */
            questionId: number;
            /** Selectedoptionid */
            selectedOptionId: number;
        };
        /** ListeningOptionRead */
        ListeningOptionRead: {
            /** Id */
            id: number;
            /** Optiontext */
            optionText: string;
        };
        /** ListeningPracticeRead */
        ListeningPracticeRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Sourcetype
             * @enum {string}
             */
            sourceType: "dialogue" | "song" | "sentences";
            /** Audiourl */
            audioUrl: string | null;
            /** Transcriptjapanese */
            transcriptJapanese: string | null;
            /** Transcriptvietnamese */
            transcriptVietnamese: string | null;
            /** Xpreward */
            xpReward: number;
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["ListeningQuestionRead"][];
        };
        /** ListeningPracticeResponse */
        ListeningPracticeResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["ListeningPracticeRead"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ListeningQuestionRead */
        ListeningQuestionRead: {
            /** Id */
            id: number;
            /** Questiontext */
            questionText: string;
            /** Sortorder */
            sortOrder: number | null;
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["ListeningOptionRead"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["AccessTokenData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** OnboardingData */
        OnboardingData: {
            /** Userid */
            userId: number;
            /** Isonboarded */
            isOnboarded: boolean;
            /**
             * Studyreason
             * @enum {string}
             */
            studyReason: "travel" | "work" | "anime_manga" | "jlpt" | "living_in_japan" | "other";
            /**
             * Targetlevel
             * @enum {string}
             */
            targetLevel: "N1" | "N2" | "N3" | "N4";
            /**
             * Dailystudyminutes
             * @enum {integer}
             */
            dailyStudyMinutes: 10 | 20 | 30 | 60;
            /**
             * Onboardedat
             * Format: date-time
             */
            onboardedAt: string;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /**
             * Studyreason
             * @enum {string}
             */
            studyReason: "travel" | "work" | "anime_manga" | "jlpt" | "living_in_japan" | "other";
            /**
             * Targetlevel
             * @enum {string}
             */
            targetLevel: "N1" | "N2" | "N3" | "N4";
            /**
             * Dailystudyminutes
             * @enum {integer}
             */
            dailyStudyMinutes: 10 | 20 | 30 | 60;
        };
        /** OnboardingResponse */
        OnboardingResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["OnboardingData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * PracticeRef
         * @description A practice item inside a lesson; fetch its content from the skill's own endpoint.
         */
        PracticeRef: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Xpreward */
            xpReward: number;
        };
        /** ProficiencyLevelListResponse */
        ProficiencyLevelListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            /** Data */
            data: components["schemas"]["ProficiencyLevelRead"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ProficiencyLevelRead */
        ProficiencyLevelRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Sortorder */
            sortOrder: number;
        };
        /** ProfileData */
        ProfileData: {
            /** Name */
            name: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Xp */
            xp: number;
            /** Streak */
            streak: number;
            /** Currentlevel */
            currentLevel: string | null;
            /** Targetlevel */
            targetLevel: string | null;
            /** Studyintention */
            studyIntention: string | null;
            /** Dailystudyminutes */
            dailyStudyMinutes: number | null;
            /**
             * Membersince
             * Format: date-time
             */
            memberSince: string;
            /** Avatarurl */
            avatarUrl: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["ProfileData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RatePronunciationRequest */
        RatePronunciationRequest: {
            /** Expectedtext */
            expectedText: string;
            /** Usertranscript */
            userTranscript: string;
            /**
             * Romaji
             * @default
             */
            romaji?: string;
        };
        /** RatePronunciationResponse */
        RatePronunciationResponse: {
            /** Score */
            score: number;
            /** Feedback */
            feedback: string;
            /** Iscorrect */
            isCorrect: boolean;
        };
        /** ReadingAnswerSubmission */
        ReadingAnswerSubmission: {
            /** Questionid */
            questionId: number;
            /** Selectedoptionid */
            selectedOptionId: number;
        };
        /** ReadingOptionRead */
        ReadingOptionRead: {
            /** Id */
            id: number;
            /** Optiontext */
            optionText: string;
        };
        /** ReadingPassageRead */
        ReadingPassageRead: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Contentjapanese */
            contentJapanese: string;
            /** Contentvietnamese */
            contentVietnamese: string | null;
            /** Xpreward */
            xpReward: number;
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["ReadingQuestionRead"][];
        };
        /** ReadingPassageResponse */
        ReadingPassageResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["ReadingPassageRead"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ReadingQuestionRead */
        ReadingQuestionRead: {
            /** Id */
            id: number;
            /** Questiontext */
            questionText: string;
            /** Sortorder */
            sortOrder: number | null;
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["ReadingOptionRead"][];
        };
        /** RefreshResponse */
        RefreshResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["AccessTokenData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** RegisterData */
        RegisterData: {
            /** Userid */
            userId: number;
            /** Isonboarded */
            isOnboarded: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Fullname */
            fullName: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["RegisterData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SRSReviewData */
        SRSReviewData: {
            /** Repetitions */
            repetitions: number;
            /** Easefactor */
            easeFactor: number;
            /** Intervaldays */
            intervalDays: number;
            /**
             * Nextreviewat
             * Format: date-time
             */
            nextReviewAt: string;
            /** Xpearned */
            xpEarned: number;
        };
        /** SRSReviewRequest */
        SRSReviewRequest: {
            /** Vocabid */
            vocabId: number;
            /**
             * Result
             * @enum {string}
             */
            result: "again" | "hard" | "good" | "easy";
        };
        /** SRSReviewResponse */
        SRSReviewResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["SRSReviewData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SkillProgress */
        SkillProgress: {
            /**
             * Skill
             * @enum {string}
             */
            skill: "vocab" | "reading" | "speaking" | "writing" | "listening";
            /** Xp */
            xp: number;
        };
        /** SubmitDialogueAttemptData */
        SubmitDialogueAttemptData: {
            /** Attemptid */
            attemptId: number;
            /** Aiscore */
            aiScore: number;
            /** Aifeedback */
            aiFeedback: string;
            /** Xpearned */
            xpEarned: number;
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
        };
        /**
         * SubmitDialogueAttemptRequest
         * @description The learner's transcripts per exchange; the server rates them and awards XP.
         */
        SubmitDialogueAttemptRequest: {
            /** Dialogueid */
            dialogueId: number;
            /** Turns */
            turns: components["schemas"]["DialogueTurnSubmission"][];
        };
        /** SubmitDialogueAttemptResponse */
        SubmitDialogueAttemptResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["SubmitDialogueAttemptData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SubmitListeningAttemptData */
        SubmitListeningAttemptData: {
            /** Attemptid */
            attemptId: number;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Xpearned */
            xpEarned: number;
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
        };
        /** SubmitListeningAttemptRequest */
        SubmitListeningAttemptRequest: {
            /** Practiceid */
            practiceId: number;
            /** Answers */
            answers: components["schemas"]["ListeningAnswerSubmission"][];
        };
        /** SubmitListeningAttemptResponse */
        SubmitListeningAttemptResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["SubmitListeningAttemptData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SubmitReadingAttemptData */
        SubmitReadingAttemptData: {
            /** Attemptid */
            attemptId: number;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Xpearned */
            xpEarned: number;
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
        };
        /** SubmitReadingAttemptRequest */
        SubmitReadingAttemptRequest: {
            /** Passageid */
            passageId: number;
            /** Answers */
            answers: components["schemas"]["ReadingAnswerSubmission"][];
        };
        /** SubmitReadingAttemptResponse */
        SubmitReadingAttemptResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            data: components["schemas"]["SubmitReadingAttemptData"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** TokenizeItem */
        TokenizeItem: {
            /** Word */
            word: string;
            /** Reading */
            reading: string;
            /** Pos */
            pos: string;
        };
        /** TokenizeRequest */
        TokenizeRequest: {
            /**
             * Text
             * @default
             */
            text?: string;
        };
        /** TokenizeResponse */
        TokenizeResponse: {
            /** Tokens */
            tokens: components["schemas"]["TokenizeItem"][];
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Fullname */
            fullName: string | null;
            /** Isonboarded */
            isOnboarded: boolean;
            /** Currentlevelid */
            currentLevelId: number | null;
            /** Lastloginat */
            lastLoginAt: string | null;
            /** Onboardedat */
            onboardedAt: string | null;
            /** Xp */
            xp: number;
            /** Streak */
            streak: number;
            /** Gems */
            gems: number;
            /** Hearts */
            hearts: number;
            /** Heartslastupdated */
            heartsLastUpdated: string | null;
            /** Lastactivitydate */
            lastActivityDate: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VocabQueueResponse
         * @description Due cards for today's SRS review session.
         */
        VocabQueueResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            /** Data */
            data: components["schemas"]["VocabularyRead"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** VocabularyListResponse */
        VocabularyListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /**
             * Businesscode
             * @default LMS-RESP-SUCCESS
             */
            businessCode: string;
            /**
             * Message
             * @default Request completed successfully.
             */
            message: string;
            /** Data */
            data: components["schemas"]["VocabularyRead"][];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** VocabularyRead */
        VocabularyRead: {
            /** Id */
            id: number;
            /** Lessonid */
            lessonId: number;
            /** Kanji */
            kanji: string | null;
            /** Kana */
            kana: string;
            /** Romaji */
            romaji: string;
            /** Meaning */
            meaning: string;
            /** Examplesentence */
            exampleSentence: string | null;
            /** Exampletranslation */
            exampleTranslation: string | null;
            /** Xpreward */
            xpReward: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AccessTokenData = components['schemas']['AccessTokenData'];
export type CourseListResponse = components['schemas']['CourseListResponse'];
export type CourseRead = components['schemas']['CourseRead'];
export type DailyActivity = components['schemas']['DailyActivity'];
export type DashboardData = components['schemas']['DashboardData'];
export type DashboardResponse = components['schemas']['DashboardResponse'];
export type DashboardUser = components['schemas']['DashboardUser'];
export type DialogueExchangeRead = components['schemas']['DialogueExchangeRead'];
export type DialogueRead = components['schemas']['DialogueRead'];
export type DialogueResponse = components['schemas']['DialogueResponse'];
export type DialogueTurnSubmission = components['schemas']['DialogueTurnSubmission'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type EvaluateWritingData = components['schemas']['EvaluateWritingData'];
export type EvaluateWritingRequest = components['schemas']['EvaluateWritingRequest'];
export type EvaluateWritingResponse = components['schemas']['EvaluateWritingResponse'];
export type GamificationStatusData = components['schemas']['GamificationStatusData'];
export type GamificationStatusResponse = components['schemas']['GamificationStatusResponse'];
export type GenerateKaiwaRequest = components['schemas']['GenerateKaiwaRequest'];
export type GenerateKaiwaResponse = components['schemas']['GenerateKaiwaResponse'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type KaiwaHistoryItem = components['schemas']['KaiwaHistoryItem'];
export type KanjiPracticeRead = components['schemas']['KanjiPracticeRead'];
export type KanjiPracticeResponse = components['schemas']['KanjiPracticeResponse'];
export type LessonDetailRead = components['schemas']['LessonDetailRead'];
export type LessonDetailResponse = components['schemas']['LessonDetailResponse'];
export type LessonListResponse = components['schemas']['LessonListResponse'];
export type LessonRead = components['schemas']['LessonRead'];
export type ListeningAnswerSubmission = components['schemas']['ListeningAnswerSubmission'];
export type ListeningOptionRead = components['schemas']['ListeningOptionRead'];
export type ListeningPracticeRead = components['schemas']['ListeningPracticeRead'];
export type ListeningPracticeResponse = components['schemas']['ListeningPracticeResponse'];
export type ListeningQuestionRead = components['schemas']['ListeningQuestionRead'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type LoginResponse = components['schemas']['LoginResponse'];
export type OnboardingData = components['schemas']['OnboardingData'];
export type OnboardingRequest = components['schemas']['OnboardingRequest'];
export type OnboardingResponse = components['schemas']['OnboardingResponse'];
export type PracticeRef = components['schemas']['PracticeRef'];
export type ProficiencyLevelListResponse = components['schemas']['ProficiencyLevelListResponse'];
export type ProficiencyLevelRead = components['schemas']['ProficiencyLevelRead'];
export type ProfileData = components['schemas']['ProfileData'];
export type ProfileResponse = components['schemas']['ProfileResponse'];
export type RatePronunciationRequest = components['schemas']['RatePronunciationRequest'];
export type RatePronunciationResponse = components['schemas']['RatePronunciationResponse'];
export type ReadingAnswerSubmission = components['schemas']['ReadingAnswerSubmission'];
export type ReadingOptionRead = components['schemas']['ReadingOptionRead'];
export type ReadingPassageRead = components['schemas']['ReadingPassageRead'];
export type ReadingPassageResponse = components['schemas']['ReadingPassageResponse'];
export type ReadingQuestionRead = components['schemas']['ReadingQuestionRead'];
export type RefreshResponse = components['schemas']['RefreshResponse'];
export type RegisterData = components['schemas']['RegisterData'];
export type RegisterRequest = components['schemas']['RegisterRequest'];
export type RegisterResponse = components['schemas']['RegisterResponse'];
export type SrsReviewData = components['schemas']['SRSReviewData'];
export type SrsReviewRequest = components['schemas']['SRSReviewRequest'];
export type SrsReviewResponse = components['schemas']['SRSReviewResponse'];
export type SkillProgress = components['schemas']['SkillProgress'];
export type SubmitDialogueAttemptData = components['schemas']['SubmitDialogueAttemptData'];
export type SubmitDialogueAttemptRequest = components['schemas']['SubmitDialogueAttemptRequest'];
export type SubmitDialogueAttemptResponse = components['schemas']['SubmitDialogueAttemptResponse'];
export type SubmitListeningAttemptData = components['schemas']['SubmitListeningAttemptData'];
export type SubmitListeningAttemptRequest = components['schemas']['SubmitListeningAttemptRequest'];
export type SubmitListeningAttemptResponse = components['schemas']['SubmitListeningAttemptResponse'];
export type SubmitReadingAttemptData = components['schemas']['SubmitReadingAttemptData'];
export type SubmitReadingAttemptRequest = components['schemas']['SubmitReadingAttemptRequest'];
export type SubmitReadingAttemptResponse = components['schemas']['SubmitReadingAttemptResponse'];
export type TokenizeItem = components['schemas']['TokenizeItem'];
export type TokenizeRequest = components['schemas']['TokenizeRequest'];
export type TokenizeResponse = components['schemas']['TokenizeResponse'];
export type UserRead = components['schemas']['UserRead'];
export type ValidationError = components['schemas']['ValidationError'];
export type VocabQueueResponse = components['schemas']['VocabQueueResponse'];
export type VocabularyListResponse = components['schemas']['VocabularyListResponse'];
export type VocabularyRead = components['schemas']['VocabularyRead'];
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    get_dashboard_api_v1_users_me_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    get_profile_api_v1_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    submit_onboarding_api_v1_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_levels_api_v1_levels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProficiencyLevelListResponse"];
                };
            };
        };
    };
    list_courses_api_v1_courses_get: {
        parameters: {
            query?: {
                levelId?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lessons_api_v1_courses__course_id__lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_v1_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lesson_vocabulary_api_v1_vocabulary_get: {
        parameters: {
            query: {
                lessonId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_v1_vocabulary_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabQueueResponse"];
                };
            };
        };
    };
    review_api_v1_vocabulary_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SRSReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SRSReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_passage_api_v1_reading_passages__passage_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passage_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingPassageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_attempt_api_v1_reading_attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReadingAttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitReadingAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_api_v1_listening_practices__practice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListeningPracticeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_attempt_api_v1_listening_attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitListeningAttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitListeningAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dialogue_api_v1_speaking_dialogues__dialogue_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dialogue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DialogueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_attempt_api_v1_speaking_attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitDialogueAttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitDialogueAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_pronunciation_api_v1_speaking_pronunciation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatePronunciationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatePronunciationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kaiwa_turn_api_v1_speaking_kaiwa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateKaiwaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateKaiwaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kanji_practice_api_v1_writing_kanji__practice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanjiPracticeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_v1_writing_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateWritingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateWritingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_gamification_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamificationStatusResponse"];
                };
            };
        };
    };
    refill_hearts_api_v1_gamification_hearts_refill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamificationStatusResponse"];
                };
            };
        };
    };
    tokenize_text_api_v1_nlp_tokenize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
