"""
API contract: request/response schemas, one module per domain (mirrors app.models).
Import from the package:

    from app.schemas import LoginRequest, UserRead
"""

from app.schemas.auth import (
    AccessTokenData,
    LoginRequest,
    LoginResponse,
    RefreshResponse,
    RegisterData,
    RegisterRequest,
    RegisterResponse,
    Token,
)
from app.schemas.base import (
    BUSINESS_SUCCESS,
    ApiResponse,
    CamelModel,
    ErrorDetail,
    ErrorResponse,
)
from app.schemas.course import (
    CourseListResponse,
    CourseRead,
    LessonDetailRead,
    LessonDetailResponse,
    LessonListResponse,
    LessonRead,
    PracticeRef,
)
from app.schemas.gamification import (
    GamificationStatusData,
    GamificationStatusResponse,
)
from app.schemas.listening import (
    ListeningAnswerSubmission,
    ListeningOptionRead,
    ListeningPracticeRead,
    ListeningPracticeResponse,
    ListeningQuestionRead,
    SubmitListeningAttemptData,
    SubmitListeningAttemptRequest,
    SubmitListeningAttemptResponse,
)
from app.schemas.lookup import (
    ProficiencyLevelListResponse,
    ProficiencyLevelRead,
    SkillCode,
)
from app.schemas.nlp import (
    TokenizeItem,
    TokenizeRequest,
    TokenizeResponse,
)
from app.schemas.onboarding import (
    DailyStudyMinutes,
    OnboardingData,
    OnboardingRequest,
    OnboardingResponse,
    StudyReason,
    TargetLevel,
)
from app.schemas.reading import (
    ReadingAnswerSubmission,
    ReadingOptionRead,
    ReadingPassageRead,
    ReadingPassageResponse,
    ReadingQuestionRead,
    SubmitReadingAttemptData,
    SubmitReadingAttemptRequest,
    SubmitReadingAttemptResponse,
)
from app.schemas.speaking import (
    DialogueExchangeRead,
    DialogueRead,
    DialogueResponse,
    DialogueTurnSubmission,
    GenerateKaiwaRequest,
    GenerateKaiwaResponse,
    KaiwaHistoryItem,
    RatePronunciationRequest,
    RatePronunciationResponse,
    SubmitDialogueAttemptData,
    SubmitDialogueAttemptRequest,
    SubmitDialogueAttemptResponse,
)
from app.schemas.user import (
    DailyActivity,
    DashboardData,
    DashboardResponse,
    DashboardUser,
    ProfileData,
    ProfileResponse,
    SkillProgress,
    UserRead,
)
from app.schemas.vocabulary import (
    ReviewResult,
    SRSReviewData,
    SRSReviewRequest,
    SRSReviewResponse,
    VocabQueueResponse,
    VocabularyListResponse,
    VocabularyRead,
)
from app.schemas.writing import (
    EvaluateWritingData,
    EvaluateWritingRequest,
    EvaluateWritingResponse,
    KanjiPracticeRead,
    KanjiPracticeResponse,
)

__all__ = [
    "AccessTokenData",
    "ApiResponse",
    "BUSINESS_SUCCESS",
    "CamelModel",
    "CourseListResponse",
    "CourseRead",
    "DailyActivity",
    "DailyStudyMinutes",
    "DashboardData",
    "DashboardResponse",
    "DashboardUser",
    "DialogueExchangeRead",
    "DialogueRead",
    "DialogueResponse",
    "DialogueTurnSubmission",
    "ErrorDetail",
    "ErrorResponse",
    "EvaluateWritingData",
    "EvaluateWritingRequest",
    "EvaluateWritingResponse",
    "GamificationStatusData",
    "GamificationStatusResponse",
    "GenerateKaiwaRequest",
    "GenerateKaiwaResponse",
    "KaiwaHistoryItem",
    "KanjiPracticeRead",
    "KanjiPracticeResponse",
    "LessonDetailRead",
    "LessonDetailResponse",
    "LessonListResponse",
    "LessonRead",
    "ListeningAnswerSubmission",
    "ListeningOptionRead",
    "ListeningPracticeRead",
    "ListeningPracticeResponse",
    "ListeningQuestionRead",
    "LoginRequest",
    "LoginResponse",
    "OnboardingData",
    "OnboardingRequest",
    "OnboardingResponse",
    "PracticeRef",
    "ProficiencyLevelListResponse",
    "ProficiencyLevelRead",
    "ProfileData",
    "ProfileResponse",
    "RatePronunciationRequest",
    "RatePronunciationResponse",
    "ReadingAnswerSubmission",
    "ReadingOptionRead",
    "ReadingPassageRead",
    "ReadingPassageResponse",
    "ReadingQuestionRead",
    "RefreshResponse",
    "RegisterData",
    "RegisterRequest",
    "RegisterResponse",
    "ReviewResult",
    "SRSReviewData",
    "SRSReviewRequest",
    "SRSReviewResponse",
    "SkillCode",
    "SkillProgress",
    "StudyReason",
    "SubmitDialogueAttemptData",
    "SubmitDialogueAttemptRequest",
    "SubmitDialogueAttemptResponse",
    "SubmitListeningAttemptData",
    "SubmitListeningAttemptRequest",
    "SubmitListeningAttemptResponse",
    "SubmitReadingAttemptData",
    "SubmitReadingAttemptRequest",
    "SubmitReadingAttemptResponse",
    "TargetLevel",
    "Token",
    "TokenizeItem",
    "TokenizeRequest",
    "TokenizeResponse",
    "UserRead",
    "VocabQueueResponse",
    "VocabularyListResponse",
    "VocabularyRead",
]
