"""redesigned entit models.

Revision ID: 07599c4355d6
Revises: 8a046a1e2dcf
Create Date: 2026-07-02 11:30:39.840653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07599c4355d6'
down_revision: Union[str, Sequence[str], None] = '8a046a1e2dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proficiency_level',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sort_order')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['proficiency_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('target_level_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['target_level_id'], ['proficiency_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('current_level_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('gems', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hearts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('hearts_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_level_id'], ['proficiency_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_profile',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_level_id', sa.Integer(), nullable=True),
    sa.Column('study_intention', sa.String(length=255), nullable=True),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_level_id'], ['proficiency_level.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_attempt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_question',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('score_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogue',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), server_default=sa.text('15'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanji_practice',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kanji', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('xp_reward', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_practice',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('transcript_japanese', sa.Text(), nullable=True),
    sa.Column('transcript_vietnamese', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_session',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chosen_level_id', sa.Integer(), nullable=True),
    sa.Column('study_intention', sa.String(length=255), nullable=True),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=True),
    sa.Column('test_attempt_id', sa.Integer(), nullable=True),
    sa.Column('result_level_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chosen_level_id'], ['proficiency_level.id'], ),
    sa.ForeignKeyConstraint(['result_level_id'], ['proficiency_level.id'], ),
    sa.ForeignKeyConstraint(['test_attempt_id'], ['test_attempt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_passage',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content_japanese', sa.Text(), nullable=False),
    sa.Column('content_vietnamese', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_attempt_answer',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_question_option',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('kanji', sa.String(length=100), nullable=True),
    sa.Column('kana', sa.String(length=100), nullable=False),
    sa.Column('romaji', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogue_attempt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogue.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogue_exchange',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=False),
    sa.Column('ja_text', sa.Text(), nullable=False),
    sa.Column('ja_romaji', sa.Text(), nullable=False),
    sa.Column('en_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dialogue_id', 'order_index')
    )
    op.create_table('kanji_practice_attempt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kanji_practice_id', sa.Integer(), nullable=False),
    sa.Column('canvas_image_url', sa.String(length=500), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kanji_practice_id'], ['kanji_practice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_attempt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('xp_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['listening_practice.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listening_question',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['listening_practice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_attempt',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('xp_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_question',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_review',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), server_default=sa.text('2.5'), nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocabulary_id')
    )
    op.create_table('listening_question_option',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['listening_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_question_option',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['reading_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_attempt_answer',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['reading_attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['reading_question.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['reading_question_option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_user_vocab_user_id'), table_name='user_vocabularies')
    op.drop_table('user_vocabularies')

    op.drop_index(op.f('idx_reading_vocabulary_items_lesson_id'), table_name='reading_vocabulary_items')
    op.drop_table('reading_vocabulary_items')

    op.drop_index(op.f('idx_reading_passages_lesson_id'), table_name='reading_passages')
    op.drop_table('reading_passages')

    op.drop_index(op.f('idx_onboarding_answers_session_id'), table_name='onboarding_answers')
    op.drop_table('onboarding_answers')

    op.drop_table('learner_profiles')

    op.drop_table('onboarding_sessions')

    op.drop_index(op.f('idx_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')

    op.drop_table('vocabularies')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vocabularies',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vocab_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ease_factor', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repetitions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_review_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_vocabularies_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabularies.id'], name=op.f('user_vocabularies_vocab_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_vocabularies_pkey'))
    )
    op.create_index(op.f('idx_user_vocab_user_id'), 'user_vocabularies', ['user_id'], unique=False)
    op.create_table('reading_vocabulary_items',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('meaning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kana', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('kanji', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('romaji', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('word_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('reading_vocabulary_items_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reading_vocabulary_items_pkey')),
    sa.UniqueConstraint('lesson_id', 'word', name=op.f('reading_vocabulary_items_lesson_word_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_reading_vocabulary_items_lesson_id'), 'reading_vocabulary_items', ['lesson_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('result_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('onboarding_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_sessions_pkey'))
    )
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('study_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('study_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('commitment_hours_per_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('learner_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('learner_profiles_pkey'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lesson_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('lessons_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    op.create_index(op.f('idx_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_table('reading_passages',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_passage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_japanese', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vietnamese_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_vietnamese', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('reading_passages_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reading_passages_pkey')),
    sa.UniqueConstraint('lesson_id', 'source_passage_id', name=op.f('reading_passages_lesson_source_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_reading_passages_lesson_id'), 'reading_passages', ['lesson_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('gems', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('hearts', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_logged_in', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('onboarded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hearts_last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_activity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name=op.f('users_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('courses_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey')),
    sa.UniqueConstraint('code', name=op.f('courses_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('onboarding_answers',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], name=op.f('onboarding_answers_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_answers_pkey')),
    sa.UniqueConstraint('session_id', 'question_code', name=op.f('onboarding_answers_session_question_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_onboarding_answers_session_id'), 'onboarding_answers', ['session_id'], unique=False)
    op.create_table('vocabularies',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('kanji', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('kana', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('romaji', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('meaning', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('example_sentence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('example_english', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vocabularies_pkey'))
    )
    op.drop_table('reading_attempt_answer')
    op.drop_table('reading_question_option')
    op.drop_table('listening_question_option')
    op.drop_table('vocabulary_review')
    op.drop_table('reading_question')
    op.drop_table('reading_attempt')
    op.drop_table('listening_question')
    op.drop_table('listening_attempt')
    op.drop_table('kanji_practice_attempt')
    op.drop_table('dialogue_exchange')
    op.drop_table('dialogue_attempt')
    op.drop_table('vocabulary')
    op.drop_table('test_question_option')
    op.drop_table('test_attempt_answer')
    op.drop_table('reading_passage')
    op.drop_table('onboarding_session')
    op.drop_table('listening_practice')
    op.drop_table('kanji_practice')
    op.drop_table('dialogue')
    op.drop_table('test_question')
    op.drop_table('test_attempt')
    op.drop_table('lesson')
    op.drop_table('learner_profile')
    op.drop_table('activity_log')
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('course')
    op.drop_table('skill')
    op.drop_table('proficiency_level')
    # ### end Alembic commands ###
