"""add vocabulary and user_vocabulary

Revision ID: 2bf0683f3fbc
Revises: 8baf3f5c2f11
Create Date: 2026-06-24 09:20:33.372736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf0683f3fbc'
down_revision: Union[str, Sequence[str], None] = '8baf3f5c2f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('kanji', sa.String(length=100), nullable=False),
    sa.Column('kana', sa.String(length=100), nullable=False),
    sa.Column('romaji', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_english', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='vocabularies_pkey')
    )
    op.create_table('user_vocabularies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_vocabularies_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabularies.id'], name='user_vocabularies_vocab_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_vocabularies_pkey')
    )
    op.create_index('idx_user_vocab_user_id', 'user_vocabularies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_vocab_user_id', table_name='user_vocabularies')
    op.drop_table('user_vocabularies')
    op.drop_table('vocabularies')
    # ### end Alembic commands ###
