"""init schemas

Revision ID: 8278f5a306ee
Revises: 
Create Date: 2026-06-11 03:37:18.301678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8278f5a306ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_orgs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='business_orgs_pkey'),
    sa.UniqueConstraint('tax_code', name='business_orgs_tax_code_key')
    )
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['content_categories.id'], name='content_categories_parent_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='content_categories_pkey'),
    sa.UniqueConstraint('slug', name='content_categories_slug_key')
    )
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='homework_pkey')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('code', name='roles_code_key')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tests_pkey'),
    sa.UniqueConstraint('code', name='tests_code_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='admin_actions_admin_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='admin_actions_pkey')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_conversations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_conversations_pkey')
    )
    op.create_index('idx_ai_conversations_user_id', 'ai_conversations', ['user_id'], unique=False)
    op.create_table('business_members',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('business_org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_role', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['business_org_id'], ['business_orgs.id'], name='business_members_business_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='business_members_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='business_members_pkey')
    )
    op.create_index('idx_business_members_org_id', 'business_members', ['business_org_id'], unique=False)
    op.create_index('idx_business_members_user_id', 'business_members', ['user_id'], unique=False)
    op.create_table('business_student_assignments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('business_org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name='business_student_assignments_assigned_by_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_org_id'], ['business_orgs.id'], name='business_student_assignments_business_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='business_student_assignments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='business_student_assignments_pkey')
    )
    op.create_index('idx_business_assignments_org_id', 'business_student_assignments', ['business_org_id'], unique=False)
    op.create_index('idx_business_assignments_user_id', 'business_student_assignments', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='courses_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    sa.UniqueConstraint('code', name='courses_code_key')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feedbacks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedbacks_pkey')
    )
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('target_language', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('study_goal', sa.Text(), nullable=True),
    sa.Column('study_mode', sa.String(length=50), nullable=True),
    sa.Column('commitment_hours_per_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learner_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='learner_profiles_pkey')
    )
    op.create_table('learning_plans',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('goal_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learning_plans_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_plans_pkey')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_level', sa.String(length=50), nullable=True),
    sa.Column('result_goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_sessions_pkey')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('business_org_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['business_org_id'], ['business_orgs.id'], name='reports_business_org_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reports_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('study_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='study_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='study_sessions_pkey')
    )
    op.create_index('idx_study_sessions_user_id', 'study_sessions', ['user_id'], unique=False)
    op.create_table('test_attempts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('level_estimate', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ai_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='test_attempts_test_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_attempts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='test_attempts_pkey')
    )
    op.create_index('idx_test_attempts_test_id', 'test_attempts', ['test_id'], unique=False)
    op.create_index('idx_test_attempts_user_id', 'test_attempts', ['user_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('score_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='test_questions_test_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='test_questions_pkey')
    )
    op.create_index('idx_test_questions_test_id', 'test_questions', ['test_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='tutor_sessions_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], name='tutor_sessions_tutor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tutor_sessions_pkey')
    )
    op.create_index('idx_tutor_sessions_student_id', 'tutor_sessions', ['student_id'], unique=False)
    op.create_index('idx_tutor_sessions_tutor_id', 'tutor_sessions', ['tutor_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastery_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_progress_pkey')
    )
    op.create_index('idx_user_progress_polymorphic', 'user_progress', ['content_type', 'content_id'], unique=False)
    op.create_index('idx_user_progress_user_id', 'user_progress', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_roles_pkey')
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('user_weaknesses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(length=100), nullable=True),
    sa.Column('topic_name', sa.String(length=255), nullable=True),
    sa.Column('weakness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_weaknesses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_weaknesses_pkey')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name='ai_messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_messages_pkey')
    )
    op.create_index('idx_ai_messages_conv_id', 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('learning_plan_steps',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('module_type', sa.String(length=100), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], name='learning_plan_steps_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='learning_plan_steps_pkey')
    )
    op.create_index('idx_learning_plan_steps_plan_id', 'learning_plan_steps', ['plan_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lesson_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='lessons_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lessons_pkey')
    )
    op.create_index('idx_lessons_course_id', 'lessons', ['course_id'], unique=False)
    op.create_table('onboarding_answers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], name='onboarding_answers_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_answers_pkey')
    )
    op.create_table('test_attempt_answers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], name='test_attempt_answers_attempt_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], name='test_attempt_answers_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='test_attempt_answers_pkey')
    )
    op.create_table('test_question_options',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], name='test_question_options_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='test_question_options_pkey')
    )
    op.create_table('tutor_session_feedback',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('pronunciation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fluency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grammar_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], name='tutor_session_feedback_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tutor_session_feedback_pkey')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('exercise_type', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('score_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='exercises_lesson_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey')
    )
    op.create_index('idx_exercises_lesson_id', 'exercises', ['lesson_id'], unique=False)
    op.create_table('lesson_resources',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('resource_url', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='lesson_resources_lesson_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lesson_resources_pkey')
    )
    op.create_table('exercise_attempts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='exercise_attempts_exercise_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='exercise_attempts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exercise_attempts_pkey')
    )
    op.create_index('idx_exercise_attempts_exercise_id', 'exercise_attempts', ['exercise_id'], unique=False)
    op.create_index('idx_exercise_attempts_user_id', 'exercise_attempts', ['user_id'], unique=False)
    op.create_table('exercise_options',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='exercise_options_exercise_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exercise_options_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_options')
    op.drop_index('idx_exercise_attempts_user_id', table_name='exercise_attempts')
    op.drop_index('idx_exercise_attempts_exercise_id', table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_table('lesson_resources')
    op.drop_index('idx_exercises_lesson_id', table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('tutor_session_feedback')
    op.drop_table('test_question_options')
    op.drop_table('test_attempt_answers')
    op.drop_table('onboarding_answers')
    op.drop_index('idx_lessons_course_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('idx_learning_plan_steps_plan_id', table_name='learning_plan_steps')
    op.drop_table('learning_plan_steps')
    op.drop_index('idx_ai_messages_conv_id', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('user_weaknesses')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_user_progress_user_id', table_name='user_progress')
    op.drop_index('idx_user_progress_polymorphic', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('idx_tutor_sessions_tutor_id', table_name='tutor_sessions')
    op.drop_index('idx_tutor_sessions_student_id', table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index('idx_test_questions_test_id', table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index('idx_test_attempts_user_id', table_name='test_attempts')
    op.drop_index('idx_test_attempts_test_id', table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_index('idx_study_sessions_user_id', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('reports')
    op.drop_table('onboarding_sessions')
    op.drop_table('notifications')
    op.drop_table('learning_plans')
    op.drop_table('learner_profiles')
    op.drop_table('feedbacks')
    op.drop_table('courses')
    op.drop_index('idx_business_assignments_user_id', table_name='business_student_assignments')
    op.drop_index('idx_business_assignments_org_id', table_name='business_student_assignments')
    op.drop_table('business_student_assignments')
    op.drop_index('idx_business_members_user_id', table_name='business_members')
    op.drop_index('idx_business_members_org_id', table_name='business_members')
    op.drop_table('business_members')
    op.drop_index('idx_ai_conversations_user_id', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_table('admin_actions')
    op.drop_table('users')
    op.drop_table('tests')
    op.drop_table('roles')
    op.drop_table('homework')
    op.drop_table('content_categories')
    op.drop_table('business_orgs')
    # ### end Alembic commands ###
