"""re-init models

Revision ID: 8a046a1e2dcf
Revises: 
Create Date: 2026-06-28 16:19:56.214707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a046a1e2dcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('gems', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hearts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('session_token', sa.String(length=512), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hearts_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('phone', name='users_phone_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('kanji', sa.String(length=100), nullable=False),
    sa.Column('kana', sa.String(length=100), nullable=False),
    sa.Column('romaji', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_english', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='vocabularies_pkey')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='courses_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    sa.UniqueConstraint('code', name='courses_code_key')
    )
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('target_language', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('study_goal', sa.Text(), nullable=True),
    sa.Column('study_mode', sa.String(length=50), nullable=True),
    sa.Column('commitment_hours_per_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learner_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='learner_profiles_pkey')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_level', sa.String(length=50), nullable=True),
    sa.Column('result_goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='onboarding_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_sessions_pkey')
    )
    op.create_table('user_vocabularies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_vocabularies_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabularies.id'], name='user_vocabularies_vocab_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_vocabularies_pkey')
    )
    op.create_index('idx_user_vocab_user_id', 'user_vocabularies', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lesson_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='lessons_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lessons_pkey')
    )
    op.create_index('idx_lessons_course_id', 'lessons', ['course_id'], unique=False)
    op.create_table('onboarding_answers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], name='onboarding_answers_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='onboarding_answers_pkey'),
    sa.UniqueConstraint('session_id', 'question_code', name='onboarding_answers_session_question_key')
    )
    op.create_index('idx_onboarding_answers_session_id', 'onboarding_answers', ['session_id'], unique=False)
    op.create_table('reading_passages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('source_passage_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_japanese', sa.Text(), nullable=False),
    sa.Column('vietnamese_title', sa.String(length=255), nullable=True),
    sa.Column('content_vietnamese', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='reading_passages_lesson_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reading_passages_pkey'),
    sa.UniqueConstraint('lesson_id', 'source_passage_id', name='reading_passages_lesson_source_key')
    )
    op.create_index('idx_reading_passages_lesson_id', 'reading_passages', ['lesson_id'], unique=False)
    op.create_table('reading_vocabulary_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('kana', sa.String(length=255), nullable=True),
    sa.Column('kanji', sa.String(length=255), nullable=True),
    sa.Column('romaji', sa.String(length=255), nullable=True),
    sa.Column('word_type', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='reading_vocabulary_items_lesson_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reading_vocabulary_items_pkey'),
    sa.UniqueConstraint('lesson_id', 'word', name='reading_vocabulary_items_lesson_word_key')
    )
    op.create_index('idx_reading_vocabulary_items_lesson_id', 'reading_vocabulary_items', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reading_vocabulary_items_lesson_id', table_name='reading_vocabulary_items')
    op.drop_table('reading_vocabulary_items')
    op.drop_index('idx_reading_passages_lesson_id', table_name='reading_passages')
    op.drop_table('reading_passages')
    op.drop_index('idx_onboarding_answers_session_id', table_name='onboarding_answers')
    op.drop_table('onboarding_answers')
    op.drop_index('idx_lessons_course_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('idx_user_vocab_user_id', table_name='user_vocabularies')
    op.drop_table('user_vocabularies')
    op.drop_table('onboarding_sessions')
    op.drop_table('learner_profiles')
    op.drop_table('courses')
    op.drop_table('vocabularies')
    op.drop_table('users')
    # ### end Alembic commands ###
