-- ==========================================
-- 1. NHÓM BẢNG ĐỘC LẬP (Tạo đầu tiên)
-- ==========================================

CREATE TABLE if NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    phone VARCHAR(20),
    status VARCHAR(50), -- hoạt động/ngưng/khóa
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP -- Lưu ý: SQLAlchemy ORM sẽ xử lý việc cập nhật cột này
);

CREATE TABLE if NOT EXISTS roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL, -- Thêm UNIQUE để tránh trùng lặp role (student/admin/etc)
    name VARCHAR(100) NOT NULL
);

CREATE TABLE if NOT EXISTS business_orgs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tax_code VARCHAR(100) UNIQUE, -- Thêm UNIQUE để tránh tạo trùng công ty
    email VARCHAR(255),
    phone VARCHAR(20),
    address TEXT,
    status VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE if NOT EXISTS tests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE,
    title VARCHAR(255) NOT NULL,
    test_type VARCHAR(100),
    total_score DECIMAL(5,2),
    duration_minutes INT,
    status VARCHAR(50)
);

CREATE TABLE if NOT EXISTS content_categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    parent_id INT,
    FOREIGN KEY (parent_id) REFERENCES content_categories(id) ON DELETE SET NULL
);

-- ==========================================
-- 2. NHÓM BẢNG GẮN VỚI USERS & ORGS
-- ==========================================

CREATE TABLE if NOT EXISTS user_roles (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS learner_profiles (
    user_id INT PRIMARY KEY,
    gender VARCHAR(20),
    dob DATE,
    target_language VARCHAR(50),
    current_level VARCHAR(50),
    target_level VARCHAR(50),
    study_goal TEXT,
    study_mode VARCHAR(50),
    commitment_hours_per_week INT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS courses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    level VARCHAR(50),
    status VARCHAR(50),
    created_by INT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE if NOT EXISTS business_members (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_org_id INT NOT NULL,
    user_id INT NOT NULL,
    member_role VARCHAR(100),
    joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (business_org_id) REFERENCES business_orgs(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS business_student_assignments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_org_id INT NOT NULL,
    user_id INT NOT NULL,
    assigned_by INT NOT NULL,
    assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50),
    FOREIGN KEY (business_org_id) REFERENCES business_orgs(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE CASCADE
);

-- ==========================================
-- 3. HỒ SƠ & ONBOARDING & LỘ TRÌNH
-- ==========================================

CREATE TABLE if NOT EXISTS onboarding_sessions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    result_level VARCHAR(50),
    result_goal TEXT,
    status VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS onboarding_answers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INT NOT NULL,
    question_code VARCHAR(100),
    question_text TEXT,
    answer_text TEXT,
    answer_value VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES onboarding_sessions(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS learning_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    target_level VARCHAR(50),
    goal_type VARCHAR(50),
    start_date DATE,
    end_date DATE,
    status VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS learning_plan_steps (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INT NOT NULL,
    step_order INT NOT NULL,
    module_type VARCHAR(100),
    content_id INT, -- Polymorphic relation (Backend phải tự xử lý Cascade Delete)
    estimated_minutes INT,
    is_required BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (plan_id) REFERENCES learning_plans(id) ON DELETE CASCADE
);

-- ==========================================
-- 4. BÀI HỌC VÀ BÀI TẬP (EXERCISES)
-- ==========================================

CREATE TABLE if NOT EXISTS lessons (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL,
    lesson_type VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    content TEXT,
    difficulty VARCHAR(50),
    estimated_minutes INT,
    status VARCHAR(50),
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS lesson_resources (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INT NOT NULL,
    resource_type VARCHAR(100),
    resource_url TEXT NOT NULL,
    description TEXT,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS exercises (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INT,
    exercise_type VARCHAR(100),
    prompt TEXT NOT NULL,
    correct_answer TEXT,
    explanation TEXT,
    score_weight DECIMAL(5,2),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE SET NULL
);

CREATE TABLE if NOT EXISTS exercise_options (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id INT NOT NULL,
    option_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS exercise_attempts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    exercise_id INT NOT NULL,
    answer_text TEXT,
    is_correct BOOLEAN,
    score DECIMAL(5,2),
    ai_feedback TEXT,
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    duration_seconds INT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
);

-- ==========================================
-- 5. BÀI KIỂM TRA (TESTS)
-- ==========================================

CREATE TABLE if NOT EXISTS test_questions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id INT NOT NULL,
    question_text TEXT NOT NULL,
    question_type VARCHAR(100),
    correct_answer TEXT,
    score_weight DECIMAL(5,2),
    sort_order INT,
    FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS test_question_options (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INT NOT NULL,
    option_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    FOREIGN KEY (question_id) REFERENCES test_questions(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS test_attempts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    test_id INT NOT NULL,
    started_at TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ,
    score DECIMAL(5,2),
    level_estimate VARCHAR(50),
    status VARCHAR(50),
    ai_reviewed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS test_attempt_answers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id INT NOT NULL,
    question_id INT NOT NULL,
    answer_text TEXT,
    is_correct BOOLEAN,
    score DECIMAL(5,2),
    FOREIGN KEY (attempt_id) REFERENCES test_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES test_questions(id) ON DELETE CASCADE
);

-- ==========================================
-- 6. THEO DÕI & AI & GIAO TIẾP
-- ==========================================

CREATE TABLE if NOT EXISTS study_sessions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    duration_minutes INT,
    study_source VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS user_progress (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    content_type VARCHAR(100),
    content_id INT NOT NULL,
    progress_percent DECIMAL(5,2),
    last_accessed_at TIMESTAMPTZ,
    mastery_level VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS user_weaknesses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    skill_type VARCHAR(100),
    topic_name VARCHAR(255),
    weakness_score DECIMAL(5,2),
    source VARCHAR(100),
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS reports (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    business_org_id INT,
    report_type VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    file_url TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (business_org_id) REFERENCES business_orgs(id) ON DELETE SET NULL
);

CREATE TABLE if NOT EXISTS ai_conversations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    context_type VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS ai_messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INT NOT NULL,
    sender_type VARCHAR(50),
    message_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    notification_type VARCHAR(100),
    title VARCHAR(255),
    body TEXT,
    channel VARCHAR(50),
    send_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    status VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS feedbacks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    category VARCHAR(100),
    content TEXT NOT NULL,
    rating INT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ==========================================
-- 7. LỚP HỌC WEBRTC & NHẬT KÝ QUẢN TRỊ
-- ==========================================

CREATE TABLE if NOT EXISTS tutor_sessions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    tutor_id INT NOT NULL,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    meeting_type VARCHAR(100),
    status VARCHAR(50),
    notes TEXT,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (tutor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS tutor_session_feedback (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INT NOT NULL,
    feedback_text TEXT,
    pronunciation_score DECIMAL(5,2),
    fluency_score DECIMAL(5,2),
    grammar_score DECIMAL(5,2),
    FOREIGN KEY (session_id) REFERENCES tutor_sessions(id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS admin_actions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INT NOT NULL,
    action_type VARCHAR(100),
    target_type VARCHAR(100),
    target_id INT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ==========================================
-- 8. TẠO INDEXES (TỐI ƯU HIỆU SUẤT POSTGRESQL)
-- PostgreSQL không tự động tạo index cho Foreign Keys. 
-- Bắt buộc phải tạo thủ công để tăng tốc độ truy vấn (JOINS & WHERES).
-- ==========================================

CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);
CREATE INDEX idx_business_members_org_id ON business_members(business_org_id);
CREATE INDEX idx_business_members_user_id ON business_members(user_id);
CREATE INDEX idx_business_assignments_org_id ON business_student_assignments(business_org_id);
CREATE INDEX idx_business_assignments_user_id ON business_student_assignments(user_id);
CREATE INDEX idx_learning_plan_steps_plan_id ON learning_plan_steps(plan_id);
CREATE INDEX idx_lessons_course_id ON lessons(course_id);
CREATE INDEX idx_exercises_lesson_id ON exercises(lesson_id);
CREATE INDEX idx_exercise_attempts_user_id ON exercise_attempts(user_id);
CREATE INDEX idx_exercise_attempts_exercise_id ON exercise_attempts(exercise_id);
CREATE INDEX idx_test_questions_test_id ON test_questions(test_id);
CREATE INDEX idx_test_attempts_user_id ON test_attempts(user_id);
CREATE INDEX idx_test_attempts_test_id ON test_attempts(test_id);
CREATE INDEX idx_study_sessions_user_id ON study_sessions(user_id);
CREATE INDEX idx_user_progress_user_id ON user_progress(user_id);
-- Index kép cho Polymorphic queries (Tìm nhanh user + content cụ thể)
CREATE INDEX idx_user_progress_polymorphic ON user_progress(content_type, content_id);
CREATE INDEX idx_ai_conversations_user_id ON ai_conversations(user_id);
CREATE INDEX idx_ai_messages_conv_id ON ai_messages(conversation_id);
CREATE INDEX idx_tutor_sessions_student_id ON tutor_sessions(student_id);
CREATE INDEX idx_tutor_sessions_tutor_id ON tutor_sessions(tutor_id);