"""simplify onboarding

Revision ID: 097d3f021135
Revises: a210a5820d62
Create Date: 2026-09-28 16:05:52.708232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '097d3f021135'
down_revision: Union[str, Sequence[str], None] = 'a210a5820d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Children before parents (foreign keys).
    op.drop_table('onboarding_session')
    op.drop_table('test_attempt_answer')
    op.drop_table('test_question_option')
    op.drop_table('test_attempt')
    op.drop_table('test_question')
    op.drop_table('test')
    op.add_column('learner_profile', sa.Column('target_level', sa.String(length=2), nullable=True))
    op.drop_constraint(op.f('learner_profile_target_level_id_fkey'), 'learner_profile', type_='foreignkey')
    op.drop_column('learner_profile', 'experience')
    op.drop_column('learner_profile', 'target_level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profile', sa.Column('target_level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('learner_profile', sa.Column('experience', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('learner_profile_target_level_id_fkey'), 'learner_profile', 'proficiency_level', ['target_level_id'], ['id'])
    op.drop_column('learner_profile', 'target_level')
    # Parents before children (foreign keys).
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('test_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('passing_score', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['target_level_id'], ['proficiency_level.id'], name=op.f('test_target_level_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    op.create_table('test_question',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('score_weight', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name=op.f('test_question_test_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_question_pkey'))
    )
    op.create_table('test_question_option',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], name=op.f('test_question_option_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_question_option_pkey'))
    )
    op.create_table('test_attempt',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('score', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name=op.f('test_attempt_test_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('test_attempt_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_attempt_pkey'))
    )
    op.create_table('test_attempt_answer',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempt.id'], name=op.f('test_attempt_answer_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], name=op.f('test_attempt_answer_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_attempt_answer_pkey'))
    )
    op.create_table('onboarding_session',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chosen_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('study_intention', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_study_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_attempt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'in_progress'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chosen_level_id'], ['proficiency_level.id'], name=op.f('onboarding_session_chosen_level_id_fkey')),
    sa.ForeignKeyConstraint(['result_level_id'], ['proficiency_level.id'], name=op.f('onboarding_session_result_level_id_fkey')),
    sa.ForeignKeyConstraint(['test_attempt_id'], ['test_attempt.id'], name=op.f('onboarding_session_test_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('onboarding_session_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_session_pkey'))
    )
    # ### end Alembic commands ###
